[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/copperstate-sale.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/cst-sale-bubble.js"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/lakes.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Access-Control-Allow-Origin = "*"
